"""Shared default configuration values for built-in token profiles."""

from typing import Final

DEFAULT_USER_ALLOWED_ALGORITHMS = ("RS256",)
DEFAULT_USER_TOKEN_TYPE = "UserAuthToken"
DEFAULT_USER_PRINCIPAL_TYPE = "USER"
DEFAULT_USER_MAX_TOKEN_AGE_SECONDS: Final[int | None] = None

DEFAULT_USER_ALLOWED_CONNECTION_METHODS: Final[tuple[str, ...]] = ("UIDPWD",)

DEFAULT_USER_CLOCK_SKEW_SECONDS = 60
DEFAULT_USER_HEADER_TYP = "JWT"
DEFAULT_USER_HEADER_ALG = "RS256"
DEFAULT_USER_PROFILE_NAME = "UserToken"

DEFAULT_AUTH0_ALLOWED_ALGORITHMS = ("RS256",)
